### ISSUE TITLE
Sorting activities by activity.date key

### ISSUE THREAD

**Issue by edmundho** [edmundho/TRACER#12]
Need help with how to sort my activities dataset by the nested `date` key. 
Can I just use .sort()?

**Comment by edmundho** [comment]
Actually, would prefer to do this on the backend with jbuilder, but can't figure it out. 

I was able to sort in my activities_controller, but the jbuilder sends it all up to the frontend sorted by id still.

**Comment by AAlfarho** [comment]
Have you checked the sort docs on MDN?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Sorting_with_map

**Comment by edmundho** [comment]
Figured it out!!!!! Made this way more complicated than it needed to be... Thanks!!
