### ISSUE TITLE
PA Review: Saving Workouts

### ISSUE THREAD

**Issue by edmundho** [edmundho/TRACER#13]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Trying to create a new workout/activity from a route crashes the app.
Let's address this before I fully review the feature.

**Comment by edmundho** [comment]
Fixed. It was an issue where I was passing in a `new Date(null)` into the React component and it did not like it.

**Comment by AAlfarho** [comment]
This MVP is almost complete, i noticed some behavior we need to address before moving on.

- [ ] Creating a new user, and then logging in, displays a loading _banner_ on the dashboard, we should have a placeholder component stating that there are no routes/activities yet for that user.
![screen shot 2018-06-14 at 4 33 09 pm](https://user-images.githubusercontent.com/1103663/41443384-6268f026-6ff1-11e8-8ae7-cf66a24c68f6.png)
- [ ] If we create a new activity by clicking the red `Log new activity button`, the title is pre-filled, however if you get there via the dropdown the title is not pre-filled. What's the delta here?
- [ ] It looks like users can delete activities that dont belong to them.
   ```ruby
     def delete
       @activity = Activity.find(params[:id])
       @activity.destroy
     end
  ```

Feel free to check the items on this list and assign this issue back to me once the mentioned points are addressed.

**Comment by edmundho** [comment]
made placeholder component
autofill logic was nested in the function that the "Log New Activity" `button` was calling.

**Comment by AAlfarho** [comment]
Good job, this MVP is now complete!
