### ISSUE TITLE
PA Review: Workout Feed

### ISSUE THREAD

**Issue by edmundho** [edmundho/TRACER#15]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Great job on the feed!

With the current state of the live site, this MVP is now complete!
