### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by edmundho** [edmundho/TRACER#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Great job on your user auth! 
I liked how you set up individual styling for the error messages on the signup form, kudos!.

The only thing I would suggest as a cosmetic change would be to make your logo _clickable_.

With the current state of your user auth feature, this MVP is completed.
