### ISSUE TITLE
PA Review: Create Routes

### ISSUE THREAD

**Issue by edmundho** [edmundho/TRACER#7]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
This MVP is almost complete, there are a couple of things to address before moving on to the next MVP.

- [ ] When visiting the link provided on your wiki `https://tracer-tracker.herokuapp.com/#/` no background is rendered.
- [ ] As part of adequate seeding, the demo user should contain at least 15-20 routes already created.
- [ ] I assume its a placeholder but let's remove the `build dat route fam`
- [ ] Creating a new route and going to the routes index `https://tracer-tracker.herokuapp.com/#/routes` is not displaying the image, there's a 403 error in the console.
- [ ] When using your search functionality and not setting any input, we are greeted with an alert message, let's handle this ourselves.
![screen shot 2018-06-12 at 10 05 28 am](https://user-images.githubusercontent.com/1103663/41305559-2841304a-6e28-11e8-8fa4-c23c6ce5c482.png)


Feel free to check the items on this list and assign this issue back to me once the mentioned points are addressed.

**Comment by edmundho** [comment]
Removed no-input alert from search.

Had to change urls from https to http to fix 403 error.

Added more seed data.

**Comment by AAlfarho** [comment]
Hi there Ed, good job addressing the above points.
With the current state of your live site, we are almost done with this MVP. 
I will close this MVP but I strongly suggest you raise independent issues to keep track of the following points. 

- [ ] I see you removed the alert message when searching with an empty string, however, now there is no feedback to the user letting him know that something went wrong.
- [ ] The routes index will look better if we had them all centered. Currently, they are not, this should be an easy fix.
![screen shot 2018-06-13 at 11 16 38 am](https://user-images.githubusercontent.com/1103663/41370600-f2b5c42e-6efc-11e8-9042-fe4aed4f095e.png)

**Comment by edmundho** [comment]
I'm not sure that the alert is necessary? If user puts searches with empty search query, nothing happens, which should be ok? Please advise.
